#!/bin/bash

# job identification number
id=1
# check if id is given as input parameter
# (like when running in condor job system)
if [ $# -ne 0 ]
then
    id=$1
fi

tar -xzf hic_3D-osg.tar.gz
sleep 2

# load necessary modules
source /cvmfs/oasis.opensciencegrid.org/osg/modules/lmod/current/init/bash
module load gcc/6.2.0 cmake boost/1.62.0 gsl/2.3 hdf5/1.8.13 python/3.5.2 all-pkgs 

export LD_LIBRARY_PATH=/cvmfs/oasis.opensciencegrid.org/osg/modules/gcc/6.2.0/lib64:/cvmfs/oasis.opensciencegrid.org/osg/modules/hdf5/1.8.13/lib:/cvmfs/oasis.opensciencegrid.org/osg/modules/libgfortran/4.4.7:/cvmfs/oasis.opensciencegrid.org/osg/modules/lapack/3.6.1/lib64:/cvmfs/oasis.opensciencegrid.org/osg/modules/atlas/3.10.1/lib64:/cvmfs/oasis.opensciencegrid.org/osg/modules/atlas/3.10.1/lib64/atlas:/cvmfs/oasis.opensciencegrid.org/osg/modules/python/3.5.2/lib:/cvmfs/oasis.opensciencegrid.org/osg/modules/gsl/2.3/lib:/cvmfs/oasis.opensciencegrid.org/osg/modules/boost/1.62.0/lib

# start trento events
####################################################################
#######################################################################
#########################################################################
###########################################################################
cd hic_3D-osg/
cp ../args.conf .
ldd fragPLUSrecomb/fragPLUSrecomb
./run-events $1

cd ../    
tar czf results$1.tar.gz hic_3D-osg/results    

transferFile=results$1.tar.gz

## transfer results
## try to be fault-tolerant
#globus() {
#  globus-url-copy \
#  -verbose -create-dest -restart -stall-timeout 30 $transferFile \
#  gsiftp://ntheoryfs01.phy.duke.edu/var/phy/project/nukeserv/yx59/summer2017/run79_AuAu200_param18/condor_00/
#}

#for i in {1..5}; do
#  globus && break
#  sleep 5 && false
#done || \
#  globus -no-data-channel-authentication -no-third-party-transfers
